# Generated by Django 5.2.1 on 2025-05-15 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_image_url_alter_customuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
