# Generated by Django 5.2.1 on 2025-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='register_as',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=10, verbose_name='Registered As'),
        ),
    ]
