service: email-api-python

provider:
  name: aws
  runtime: python3.9

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send
          method: post

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  serverless-offline:
    httpPort: 3000
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - .env